on:
 push:
   branches: master
name: Check markdown links
jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Link Checker
        uses: peter-evans/link-checker@v1
        with:
         args: README.md
      - name: Create Issue From File
        uses: peter-evans/create-issue-from-file@v2
        with:
          title: "[Bot] Broken Links Report"
          content-filepath: ./link-checker/out.md
          labels: report
